name: Build and Push to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - '**/*.py'
      - '.github/workflows/docker-publish.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: vars
        run: echo "imagename=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Build Docker image (minimal + geospatial)
        run: |
          docker build -t ${{ env.imagename }}:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ${{ env.imagename }}:latest
